### PR TITLE
Add IteratedDataSnapshot interface to match with firebase admin v12

### LINKED ISSUE #1515: regression in "Build failed with error TS2416 in firebase-functions"
I'm filing this because there's been a serious regression on an old issue and there's a lot of discussion/new comments that aren't being responded to, I believe due to the issue being closed. Can we get some eyes on it?

Issue that's regressed: https://github.com/firebase/firebase-functions/issues/1442

### PR DESCRIPTION
**Pull request by colerogers**
Fixes #1515 #1516

### CODE REVIEW

**Comment by sceee** [comment]
Fixes: #1513

**Review by blidd-google — APPROVED** [review]
LGTM, changelog entry?

**Comment by baraknaveh** [comment]
Thanks for fixing this!

**Comment by NathanC** [comment]
@colerogers @sceee what is the release cadence/when can I expect to be able to pick up this change?

**Pull request merged**
