### PR TITLE
Add v2 Remote Config Triggers

### PR DESCRIPTION
**Pull request by colerogers**
Adds remote config triggers to CF3v2

```
import { onConfigUpdated } from 'firebase-functions/v2/remoteConfig';

export const fn = onConfigUpdated((event) => { console.log("hello world"); });
```

### CODE REVIEW

**Review by TheIronDev — APPROVED** [review]
LGTM!

**Review by taeold — APPROVED** [review]
Loving the doc comments. Do you want to mark these triggers as @alpha until we have samples/docs/CLI support merged and released?

**Review by taeold — APPROVED** [review]
One more thing - do you want to add integration test target for this (in this PR or later in another PR).

**Comment by colerogers** [comment]
@taeold - added the `@alpha` tags & since this change requires CLI changes to be released, I'll follow up with a int test in another PR

**Pull request merged**
