### PR TITLE
add firebase-admin@11.0.0 to peerDependencies

### PR DESCRIPTION
**Pull request by Manokii**
### Description
Some CI fails after upgrading to [firebase-admin@11.0.0][fa]. 

This is because firebase cloud-functions does not recognize [firebase-admin@11.0.0][fa] as peer dependency

fixes: #1147

closing #1151 and opening this new pr using `launch.next` branch 

[fa]: https://github.com/firebase/firebase-admin-node/releases/tag/v11.0.0 "firebase-admin@11.0.0"

### CODE REVIEW

**Comment by taeold** [comment]
Thanks!

**Comment by MauriceArikoglu** [comment]
@taeold when do you expect this to land?

**Comment by r-dev-limited** [comment]
merge ?

**Review by inlined — APPROVED** [review]

**Comment by inlined** [comment]
We're still working out a timeline for vNext, though it should be "soon". If it turns out to be an unreasonable amount of time we'll release a patch update that adds the new peer dependency.

**Comment by radvansky-tomas** [comment]
Thx for quick merge, we can only hope for patch/new version now...

**Comment by MauriceArikoglu** [comment]
@radvansky-tomas @Manokii w 3.22.0 is out I just saw (3d ago)

**Pull request merged**
