### PR TITLE
Fix onRequest handler return type to allow promises (async)

### PR DESCRIPTION
**Pull request by p-young**
### Description

Fixes the types for onRequest so that it allows for async function handlers (returning a Promise)

### CODE REVIEW

**Comment by sk-** [comment]
@p-young This seems to be a duplicate of #696 (which is already merged).

**Comment by p-young** [comment]
@sk- Ah yea I was just making a similar change so that the type is exposed in the function builder (which is where I end up needing it).

Check the files changed, let me know if that makes sense / is the right thing

**Comment by sk-** [comment]
Thanks @p-young for the clarification. That definition was indeed missing.

**Comment by sk-** [comment]
Note that the PR is out of sync with the base branch.

**Comment by sk-** [comment]
@laurenzlong Any chance this could be merged?

**Pull request merged**
