### PR TITLE
Define Codeowners

### PR DESCRIPTION
**Pull request by merlinnot**
### Description

This PR introduces a [Codeowners](https://help.github.com/en/articles/about-code-owners) file, which will assign @thechenky automatically to all incoming PRs, so I don't need to ping her each time 😃

### Code sample

Not relevant.

### CODE REVIEW

**Comment by merlinnot** [comment]
@thechenky

**Comment by thechenky** [comment]
Hahaha, this is great 💯😄

**Comment by thechenky** [comment]
Can we add @kevinajian to the owner file too?

**Comment by merlinnot** [comment]
Sure!

**Pull request merged**
