### PR TITLE
Add emulator app override function

### PR DESCRIPTION
**Pull request by samtstern**
### Description

This is motivated by:
https://github.com/firebase/firebase-tools/issues/1682

Internally this will allow the emulator suite to do this:
```js
const app = admin.initializeApp();
functions.app.setEmulatedAdminApp(app);
```

This way, things like `change.after.ref` will not point to production Firestore but will instead point to the emulator.

### Code sample

See above.

### CODE REVIEW

**Comment by ralcar** [comment]
I think I am doing this wrong because i get an error. Im running firebase-admin 8.30 and firebase-functions 3.3.0.

My setup in the functions folder is:
**src/index.ts**
Here i load a file called main.ts first

**src/main.ts**
```
import { initializeApp, credential } from 'firebase-admin';
initializeApp();

... << initialize two other databases using credential.cert()

export * from 'firebase-functions';
```
I changed this to:
```
import { initializeApp, credential } from 'firebase-admin';
import * as functions from 'firebase-functions';
const app = initializeApp();
functions.app.setEmulatedAdminApp(app);

... << initialize two other databases using credential.cert()

export * from 'firebase-functions';
```

And the "firebase emulators:start" get this error:

```
functions: TypeError: mod.hasOwnProperty is not a function
    at extractTriggers (C:\Users\ralcar\AppData\Roaming\npm\node_modules\firebase-tools\lib\extractTriggers.js:5:17)
    at extractTriggers (C:\Users\ralcar\AppData\Roaming\npm\node_modules\firebase-tools\lib\extractTriggers.js:22:17)
    at extractTriggers (C:\Users\ralcar\AppData\Roaming\npm\node_modules\firebase-tools\lib\extractTriggers.js:22:17)
    at C:\Users\ralcar\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:684:38
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\ralcar\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:4:58)     
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
!  Your function was killed because it raised an unhandled error.
```

Am i doing this wrong or this another defect?

**Comment by samtstern** [comment]
@ralcar I believe you're running into this issue:
https://github.com/firebase/firebase-tools/issues/1687

It will be fixed in the next version of `firebase-tools`

**Comment by ralcar** [comment]
@samtstern ahh ok yes it looks like so, thank you

**Comment by lookfirst** [comment]
No tests?

**Pull request merged**
