### PR TITLE
Generate documentation with api-extractor

### PR DESCRIPTION
**Pull request by taeold**
This picks up where https://github.com/firebase/firebase-functions/pull/984 had left off.

This gets us started with generating docs using api-extractor. By no means it's complete - I wanted us to generate the doc and see the output as we incrementally improve the reference docs.

Separately, I'm going to be pushing out PRs to suppress many warnings generated by api-extractor (e.g. mostly on missing documentation/annotation).

To generate reference doc for v2, run the following command:

```
$ npm i
$ npm run build
$ npm run docgen:v2
```

Documents should be generated in `docgen/v2/markdown` folder.

### CODE REVIEW

**Comment by egilmorez** [comment]
Looking like a great start in an encouraging direction!  Staged the output from this branch internally at:

https://firebase.devsite.corp.google.com/docs/functions/beta/reference/firebase-functions.md?db=egilmore-v2preview#firebase-functions_package

Two things to observe there:

-- The _toc.yaml file isn't generating entries for all the generated pages.

-- There are a lot of empty "description" fields that we should address in the source.

**Comment by shauryaaher** [comment]
Looks like you can't merge this.

**Review by colerogers — APPROVED** [review]
Not sure if you wanted to keep this PR open or merge

**Comment by egilmorez** [comment]
In addition to generating the TOC, we will need a small tweak to *include* the TOC for the preview:

Wherever "{% extends "_internal/templates/reference.html" %}" is specified, we need to change it to "{% extends "_internal/templates/generic.html" %}.  

With that change, we can have our own nested reference TOC as shown in this internal staging link: https://firebase.devsite.corp.google.com/docs/functions/beta/reference/firebase-functions?db=egilmore-v2preview

**Review by shauryaaher — CHANGES_REQUESTED** [review]
Please create a new PR. This is out-of-date. This PR must be closed.

**Comment by egilmorez** [comment]
Apologies -- I meant to comment on related PR 1097.

**Pull request merged**
