### PR TITLE
Fall back to updateTime if no readTime exists

### LINKED ISSUE #599: Firestore: ReadTime not populated
See https://github.com/firebase/firebase-js-sdk/issues/2459

It looks like `data.value.readTime` does not exist for a Firestore Event. When testing, this causes `snapshotConstructor` [to set the readTime argument](https://github.com/firebase/firebase-functions/blob/master/src/providers/firestore.ts#L157) to `undefined`. If the read time is not available, we should use the update or create time of a document.

### PR DESCRIPTION
**Pull request by iwikal**
### Description

Fixes #599. It seemed to work when I tested it in the emulator.

### CODE REVIEW

**Comment by iwikal** [comment]
@googlebot I signed it!

**Comment by inlined** [comment]
Per comment in this bug, should it be the `updateTime` or should it be the event timestamp?

**Review by inlined — APPROVED** [review]

**Comment by iwikal** [comment]
All up to date now! I don't understand why the CI isn't completing though.

**Comment by iwikal** [comment]
@inlined Is there something else I need to do before this can be merged?

**Comment by inlined** [comment]
No, there was nothing left to do. Did you not have permission to merge yourself after I approved? Either way, I committed the change.

**Comment by iwikal** [comment]
Nope, no merge button on my end.

**Comment by MauriceArikoglu** [comment]
This is not working still @iwikal - tested on 3.22.0

**Pull request merged**
