### PR TITLE
Run Prettier and TSLint in the CI

### PR DESCRIPTION
**Pull request by merlinnot**
### Description

This PR introduces two new scripts: `format:fix` and `lint:fix`, which runs Prettier and TSLint with autofixers. It also changes a behaviour of `format` to report issues. Both are now run in the CI, in parallel with tests.

I fixed all linter errors, so the CI passes. All changes in source files are autofixes made by TSLint.

### Code sample

Not relevant.

### CODE REVIEW

**Comment by merlinnot** [comment]
@thechenky Unfortunately I don't have permissions to assign you as a reviewer, as requested in the previous PR.

**Comment by thechenky** [comment]
Tests are failing for me here: 

```
  276 passing (510ms)
  2 failing

  1) Database Functions
       process.env.FIREBASE_CONFIG not set
         should throw when trigger is accessed:
     AssertionError: expected [Function] to throw Error
      at Context.it (spec/providers/database.spec.ts:418:17)

  2) Storage Functions
       process.env.FIREBASE_CONFIG not set
         should throw when trigger is accessed:
     AssertionError: expected [Function] to throw Error
      at Context.it (spec/providers/storage.spec.ts:550:78)
```

**Comment by merlinnot** [comment]
Tests are passing for me locally and in the CI (it's not fully done yet, but tests passed already). Maybe you could try again after running `npm install`?

**Comment by merlinnot** [comment]
@thechenky The CI is now green, all steps.

**Comment by thechenky** [comment]
@merlinnot yeah, something weird is happening for me - they're not passing even on master on your fork which is synced with master on this repo, but passing on master on this repo. Should be okay, I see the CI is green too.

**Pull request merged**
