### PR TITLE
Wrap v2 firestore functions with trace context

### PR DESCRIPTION
**Pull request by milo-**
### Description

Wrap handlers with trace context. Fixes https://github.com/firebase/firebase-functions/issues/1439

### CODE REVIEW

**Review by blidd-google — CHANGES_REQUESTED** [review]
LGTM, please update the changelog before merging changes.

**Comment by milo-** [comment]
Thanks @blidd-google, changelog added

**Review by blidd-google — APPROVED** [review]
Looks great!

**Comment by lox** [comment]
Might it be possible to get this released?

**Comment by tonylampada** [comment]
Is there a way I can import and use the wrap handler myself while this doesn't get released?

**Comment by milo-** [comment]
@blidd-google Would it be possible to get this released? It would massively help debugging.

**Comment by ciriousjoker** [comment]
@blidd-google It's been almost 4 months since you merged this, is there an eta for when this is released? Seems like #1331 is also blocked by this.

**Pull request merged**
